### ISSUE TITLE
S3 permission for accessing objects

### ISSUE THREAD

**Issue by Sheshan-sheshu** [awsdocs/amazon-s3-developer-guide#104]
Im uploading a video to S3 from Java, I need permission as shown in the image below.
i have tried with few option like :-

	request.setMetadata(metadata); //request is object of PutObjectRequest

            option 1-->  request.setCannedAcl(CannedAccessControlList.PublicRead);
                
                
           option 2--> AccessControlList acl = new AccessControlList();
                               acl.grantPermission(GroupGrantee.AllUsers, Permission.FullControl); 
                               request.setAccessControlList(acl);

				
However Im not getting expected result as shown in image, let me know if i can get any solution for the same.

![aws_permission_error](https://user-images.githubusercontent.com/69001272/89192687-79ad6580-d5c2-11ea-94ef-ccab78bc25e7.jpg)

**Comment by panjws** [comment]
Hi, 

This seems like this is a support issue specific to your needs.

If you are still having issues and want further support, you can:
•	Post your questions on the [Amazon S3 discussion forum](https://forums.aws.amazon.com/tags/s3?categoryID=1)
•	Or contact [Technical Support ](https://aws.amazon.com/contact-us/)

If there is something specific missing in our docs, please let us know. 
Otherwise, I shall close this issue.

Best regards and thanks for being an AWS Customer,

panjws
